---
- name: install packages
  action: yum name={{ item }}
  with_items:
    - rsync
    - opennebula-node-kvm

- name: configure udev
  action: copy src=80-kvm.rules dest=/etc/udev/rules.d/80-kvm.rules owner=root group=root mode=644

- name: configure libvirt
  action: template src=libvirtd.conf.j2 dest=/etc/libvirt/libvirtd.conf 
  notify: restart libvirtd

- name: synchronize oneadmin ssh keys
  action: synchronize dest=/var/lib/one/.ssh/ src=/var/lib/one/.ssh/ delete=yes
  delegate_to: "{{ mgmt_host }}"

- name: configure ssh authorized keys
  action: authorized_key user=oneadmin key="{{ lookup('file', '/var/lib/one/.ssh/' + item  ) }}"
  with_items:
    - id_rsa.pub

- name: set SELinux label on authorized_keys
  action: file path=/var/lib/one/.ssh/authorized_keys setype=ssh_home_t

