---
project_name: "ceph"


####################
# Ceph
####################

ceph_release: jewel
ceph_cluster_fsid:
ceph_mon_hosts:
# ceph_keys:
#  opennebula: <cephxkey>
ceph_keys:
ceph_libvirt_secret_uuid:
