---
project_name: "one_kvmnode"

mgmt_host: "{{ groups['one-mgmt'][0] }}"
ansible_ssh_port: 22
# 5900:6000 NoVNC Ports
# 49152:49216 Live migration
in_ports:
  - 5900:6000
  - 49152:49216

####################
# libvirt imports
####################

# for ovirt:
libvirt_sasl:
  opennebula: opennebula
